import type { UserRole } from './types';

/**
 * Role → navigation. Mirrors docs/role-navigation.md.
 *
 * This hides things for usability. It is NOT the security boundary — the API
 * enforces that, and assumes any client can call any endpoint directly. If
 * this file and the backend's @Roles() ever disagree, the backend wins and
 * this file is the bug.
 */

export interface NavItem {
  label: string;
  href: string;
  icon: string;
  /** Not built yet — rendered as a placeholder rather than a broken link. */
  phase?: number;
}

const NAV: Record<UserRole, NavItem[]> = {
  DOCTOR: [
    { label: "Today's Queue", href: '/queue', icon: '▤' },
    { label: 'Appointments', href: '/appointments', icon: '▦' },
    { label: 'Patients', href: '/patients', icon: '◍' },
  ],
  RECEPTIONIST: [
    { label: 'Check-in Queue', href: '/check-in', icon: '▤' },
    { label: 'Appointments', href: '/appointments', icon: '▦' },
    { label: 'Register Patient', href: '/patients/new', icon: '+' },
    { label: 'Patients', href: '/patients', icon: '◍' },
    { label: 'Doctors', href: '/doctors', icon: '✚' },
  ],
  NURSE: [
    { label: 'Ward Board', href: '/ward', icon: '▥' },
    { label: 'Vitals', href: '/vitals', icon: '♥' },
    { label: 'Medications', href: '/medications', icon: '℞' },
    { label: 'Appointments', href: '/appointments', icon: '▦' },
    { label: 'Patients', href: '/patients', icon: '◍' },
  ],
  PHARMACIST: [
    { label: 'Prescription Queue', href: '/pharmacy/queue', icon: '▤' },
    { label: 'Inventory', href: '/pharmacy/inventory', icon: '▨' },
    { label: 'Patients', href: '/patients', icon: '◍' },
  ],
  BILLING_STAFF: [
    { label: 'Invoices', href: '/billing/invoices', icon: '▤' },
    { label: 'Payments', href: '/billing/payments', icon: '＄' },
    { label: 'Patients', href: '/patients', icon: '◍' },
  ],
  ADMIN: [
    { label: 'Dashboard', href: '/admin', icon: '▨' },
    { label: 'Reports', href: '/admin/reports', icon: '◪' },
    { label: 'Daily Activity', href: '/admin/activity', icon: '☰' },
    { label: 'Staff & Users', href: '/admin/users', icon: '◍' },
    { label: 'Departments', href: '/admin/departments', icon: '▢' },
    { label: 'Clinic Settings', href: '/admin/settings', icon: '⚙' },
    { label: 'Doctors', href: '/doctors', icon: '✚' },
    { label: 'Appointments', href: '/appointments', icon: '▦' },
    { label: 'Patients', href: '/patients', icon: '◍' },
    { label: 'Audit Log', href: '/audit', icon: '⌾' },
  ],
};

export function navFor(role: UserRole): NavItem[] {
  return NAV[role] ?? [];
}

/** Where a role lands after login — the screen it spends the day on. */
export function landingFor(role: UserRole): string {
  return navFor(role)[0]?.href ?? '/patients';
}

/**
 * Which roles may reach a given screen, derived from NAV rather than declared
 * separately.
 *
 * WHY THIS EXISTS SEPARATELY FROM THE MENU
 * ----------------------------------------
 * Hiding a link stops nobody from arriving at the URL. An administrator signed
 * in with `?next=/queue` still in the address bar — carried over from whoever
 * used the browser last — landed on the doctor's queue, which called
 * `GET /me/queue` and got a 403. The API refused, exactly as designed, so
 * nothing leaked. But the screen was broken, and the attempt was written into
 * the hospital's audit log as a denied clinical access by an admin: a security
 * event that reads as somebody probing, generated by the app itself.
 *
 * A rule that only shapes a menu is a rule that holds until the first URL is
 * typed.
 *
 * NOT A SECURITY BOUNDARY, STILL
 * ------------------------------
 * The API remains the boundary and assumes any client can call any endpoint.
 * This stops the app from *asking* for what its own role cannot have.
 */
const ROUTE_ROLES: Record<string, UserRole[]> = (() => {
  const map: Record<string, UserRole[]> = {};
  for (const role of Object.keys(NAV) as UserRole[]) {
    for (const item of NAV[role]) (map[item.href] ??= []).push(role);
  }
  return map;
})();

/** Every screen the app renders. Unknown paths are 404s, not denials. */
export function isKnownRoute(path: string): boolean {
  return normalise(path) in ROUTE_ROLES;
}

/**
 * May this role open this screen?
 *
 * Unknown paths return `true`: a typo should reach Next's not-found page, not
 * be silently rewritten to the role's landing screen as though it were
 * forbidden. Only a route that exists *and* belongs to other roles is refused.
 */
export function canReach(role: UserRole, path: string): boolean {
  const roles = ROUTE_ROLES[normalise(path)];
  return roles ? roles.includes(role) : true;
}

/** Strips the query, hash and any trailing slash. `/patients/` is `/patients`. */
function normalise(path: string): string {
  const bare = path.split(/[?#]/)[0];
  return bare.length > 1 && bare.endsWith('/') ? bare.slice(0, -1) : bare;
}

export const ROLE_LABEL: Record<UserRole, string> = {
  ADMIN: 'Administrator',
  DOCTOR: 'Doctor',
  NURSE: 'Nurse',
  RECEPTIONIST: 'Reception',
  PHARMACIST: 'Pharmacy',
  BILLING_STAFF: 'Billing',
};
