-- Tax on what a hospital sells.
--
-- HAND-WRITTEN, like the four before it. Verify it with:
--
--   npm run db:verify
--
-- which diffs the LIVE database against the schema. Before applying, it prints
-- the DDL this file is supposed to contain — compare the two. After applying,
-- it should print nothing, which is the proof that this file and the schema
-- agree.
--
-- Not `--from-migrations`: that replays the whole migration history into a
-- scratch database and so demands `--shadow-database-url`, which this project
-- has never had. It has caught three people out now, including on the last
-- three hand-written migrations, so the working form is a script rather than
-- something to remember.
--
-- And afterwards, ALWAYS:
--
--   npm run db:rls
--
-- `tax_rates` is a tenant-scoped table and does NOT get its policy from this
-- file. Without that step it is readable across hospitals — which for a table
-- naming what a competitor charges is a real disclosure, not a theoretical one.
--
-- APPLIED. Do not edit this file.
--
-- Prisma records a checksum for every applied migration, so changing one that
-- has run makes the history inconsistent: the next `migrate deploy` refuses,
-- and across two deployments the same migration name comes to mean two
-- different things. That happened once here — `tax_rate_components` was added
-- to this file after it had been applied, and the API then queried a table
-- Postgres did not have. It lives in `20260903170000_tax_components` now.
-- New work is a new file, always.

-- ---------------------------------------------------------------------------
-- Rates a hospital defines for itself.
-- ---------------------------------------------------------------------------
CREATE TABLE "tax_rates" (
  "id"              SERIAL PRIMARY KEY,
  "tenantId"        INTEGER NOT NULL REFERENCES "tenants"("id"),
  "name"            TEXT NOT NULL,
  -- Basis points. 1250 = 12.5%. Integer for the same reason money is held in
  -- minor units: a rate is compared and summed, and a float is a trap.
  "rateBasisPoints" INTEGER NOT NULL DEFAULT 0,
  "isDefault"       BOOLEAN NOT NULL DEFAULT false,
  "isActive"        BOOLEAN NOT NULL DEFAULT true,
  "createdAt"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  -- A rate above 100% is a typo — somebody typing a percentage where basis
  -- points were wanted. Enforced here as well as in the DTO, because the
  -- constraint is the guarantee and the check is only for the message.
  CONSTRAINT "tax_rates_rate_sane" CHECK ("rateBasisPoints" BETWEEN 0 AND 10000)
);

CREATE UNIQUE INDEX "tax_rates_tenantId_name_key" ON "tax_rates"("tenantId", "name");
CREATE INDEX "tax_rates_tenantId_idx" ON "tax_rates"("tenantId");

-- Exactly one default per hospital. A partial unique index rather than an
-- application check: two defaults would make the rate applied to an unassigned
-- medicine depend on row order, which is the kind of bug that shows up as an
-- unexplained penny difference months later.
CREATE UNIQUE INDEX "tax_rates_one_default_per_tenant"
  ON "tax_rates"("tenantId") WHERE "isDefault";

-- ---------------------------------------------------------------------------
-- What each medicine is taxed at. Null means the tenant default, so switching
-- tax on does not require touching every catalogue row first.
-- ---------------------------------------------------------------------------
ALTER TABLE "medicines" ADD COLUMN "taxRateId" INTEGER;
ALTER TABLE "medicines"
  ADD CONSTRAINT "medicines_taxRateId_fkey"
  FOREIGN KEY ("taxRateId") REFERENCES "tax_rates"("id") ON DELETE SET NULL;
CREATE INDEX "medicines_taxRateId_idx" ON "medicines"("taxRateId");

-- ---------------------------------------------------------------------------
-- Per-hospital settings.
-- ---------------------------------------------------------------------------

-- Off by default, and an explicit switch rather than "are there any rates".
-- A hospital sets its rates up, checks them, and turns tax on when ready; an
-- implicit switch would mean the first rate created starts taxing every sale.
-- Every existing hospital therefore keeps behaving exactly as it does today.
ALTER TABLE "tenants" ADD COLUMN "taxEnabled" BOOLEAN NOT NULL DEFAULT false;

-- Default false: tax added at the till, which is the US shape and is also what
-- "no tax at all" already looked like. A hospital in India switches it on
-- because its printed MRPs already include GST.
ALTER TABLE "tenants" ADD COLUMN "pricesIncludeTax" BOOLEAN NOT NULL DEFAULT false;

-- Separate from the medicine default on purpose: Indian healthcare services
-- are largely exempt while the medicines dispensed at the same visit are not.
ALTER TABLE "tenants" ADD COLUMN "consultationTaxRateId" INTEGER;

-- ---------------------------------------------------------------------------
-- What was actually charged, captured on the line.
-- ---------------------------------------------------------------------------
-- Copied rather than referenced, exactly like `unitPrice` and `medicineName`:
-- changing a rate next year must not restate what a patient was charged last
-- year. The name is stored too so an old invoice reads correctly even if the
-- rate has since been renamed or retired.
ALTER TABLE "invoice_items" ADD COLUMN "taxRateBasisPoints" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "invoice_items" ADD COLUMN "taxRateName" TEXT;
ALTER TABLE "invoice_items" ADD COLUMN "taxAmount" DECIMAL(10,2) NOT NULL DEFAULT 0;

-- Existing rows: zero tax, which is what they were charged. `amount` on those
-- rows is both the net and the gross, and stays correct under the new reading.
