-- AlterTable
ALTER TABLE "tenants" ADD COLUMN     "clinicEndHour" INTEGER NOT NULL DEFAULT 17,
ADD COLUMN     "clinicStartHour" INTEGER NOT NULL DEFAULT 9,
ADD COLUMN     "slotMinutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "timezone" TEXT NOT NULL DEFAULT 'UTC';
